### ISSUE TITLE
Infinite "connecting to beehive" loop

### ISSUE THREAD

**Issue by EvieTheOwl** [hive365/BugReports#5]
__Submitted by ErasedRhythm__

**Describe the bug**
Connecting to bee hive.
I was able to reproduce a infinite "connecting to BeeHive". First I opened to App normally and the app started without issues and the stream started automatically. Switched to home screen, opened the Playstore and opened the app again, using the open function when viewing the app. The app is now in an infinite connecting to BeeHive mode and both album and dj is displayed as Hive365 Logo. Or at least it is connecting for a really long time.

**Smartphone (please complete the following information):**
Version 2.1.4  
Huawai P20  
Android 10

**Comment by profjb58** [comment]
Fixed in latest development release. Just removed the scrollview :P

**Comment by profjb58** [comment]
Changed the launch mode from the Android XML file which seems to have fixed it

**Comment by EvieTheOwl** [comment]
Changed launch mode to single instance from within the Android XML file which seems to have fixed it
