### ISSUE TITLE
Submission Fails

### ISSUE THREAD

**Issue by ErasedRhythm** [hive365/BugReports#8]
Platform
Web-Player API

Description
Using the web-player or any other kind of API-Call to the URL `https://hive365.co.uk/web_player/gadget-rating.php` results with the message `Failed to submit rating, Please try again`. 

This probably has something to to with the usage of IPv6. Needs more info.

How to reproduce:
2. Start the web-player
3. Use one of the buttons: '!Choon', '!Poon' or '!DJftw'

Log files (optional)
![image](https://user-images.githubusercontent.com/34625207/116793071-d479dc00-aac4-11eb-96e5-0312fb4725f3.png)

**Comment by Coolguy3289** [comment]
Can confirm, this is due to how the back-end handles the submissions when IPv6 is involved.

**Comment by ErasedRhythm** [comment]
This was fixed a while ago. Closing the issue.
